language: java
jdk:
  - openjdk8

# Travis Ci를 어느 브랜치가 푸시될 때 수행할지 지정
branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때 수행하는 명령어로 여기서는 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행
script: "./gradlew clean build"

before_deploy:
  - zip -r dolphin-springboot2-webservice *
  - mkdir -p deploy
  - mv dolphin-springboot2-webservice.zip deploy/dolphin-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: dolphin-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

#codedeploy 추가
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: dolphin-springboot-build
    key: dolphin-springboot2-webservice.zip
    bundle_type: zip
    application: dolphin-springboot2-webservice
    deployment_group: dolphin-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hawrang17@naver.com